language: python

python:
- "3.6"
sudo: required
env:
- DJANGO=2.1.3
services:
- mysql
- redis-server
before_install:
- sudo mysql -e 'CREATE DATABASE piano_cabin DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
- sudo mysql -e "SHOW VARIABLES LIKE 'character_set_%';"
- sudo mysql -e "SHOW VARIABLES LIKE 'collation_%';"
install:
- pip install -r ./Backend/requirements.txt
before_script:
- mv ./Backend/configs.example.json ./Backend/configs.json
script:
- cd Backend
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test