language: python

python:
- "3.6"
sudo: required
env:
- DJANGO=2.1.3
services:
- mysql
- redis-server
before_install:
- sudo cat ./Backend/mysql.cnf >> /etc/mysql/my.cnf
- sudo cat ./Backend/mysql.cnf >> /etc/mysql/mysql.cnf
- sudo service mysql restart
- sudo mysql -e 'CREATE DATABASE piano_cabin DEFAULT CHARACTER SET utf8;'
install:
- pip install -r ./Backend/requirements.txt
before_script:
- mv ./Backend/configs.example.json ./Backend/configs.json
script:
- cd Backend
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test
