# Generated by Django 2.1.3 on 2018-11-14 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('feedback_time', models.DateTimeField(default='2018-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='LongTermOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='2018-01-01')),
                ('end_date', models.DateField(default='2018-01-01')),
                ('day_in_week', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(default='2018-01-01')),
                ('end_time', models.DateTimeField(default='2018-01-01')),
                ('price', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
                ('payment_status', models.IntegerField(default=1)),
                ('order_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('publish_time', models.DateTimeField(default='2018-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2018-01-01')),
                ('start_time', models.DateTimeField(default='2018-01-01')),
                ('end_time', models.DateTimeField(default='2018-01-01')),
                ('price', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=1)),
                ('order_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PianoRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.TextField(default='')),
                ('piano_type', models.TextField(default='')),
                ('brand', models.TextField(default='')),
                ('prices', models.TextField(default='{"student":-1,"teacher":-1,"other":-1}')),
                ('usable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.TextField(default='')),
                ('identity', models.TextField(default='')),
                ('permission', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='piano_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.PianoRoom'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
        migrations.AddField(
            model_name='longtermorder',
            name='piano_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.PianoRoom'),
        ),
        migrations.AddField(
            model_name='longtermorder',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
    ]
