# Generated by Django 2.1.3 on 2018-12-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.TextField(default='')),
                ('feedback_content', models.TextField(default='')),
                ('read_status', models.BooleanField(default=False)),
                ('feedback_time', models.DateTimeField(default='2018-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='LongTermOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='2018-01-01')),
                ('end_date', models.DateField(default='2018-01-01')),
                ('day_in_week', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(default='2018-01-01')),
                ('end_time', models.DateTimeField(default='2018-01-01')),
                ('price', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(default='')),
                ('news_content', models.TextField(default='')),
                ('publish_time', models.DateTimeField(default='2018-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=128, unique=True)),
                ('date', models.DateField(default='2018-01-01')),
                ('start_time', models.DateTimeField(default='2018-01-01')),
                ('end_time', models.DateTimeField(default='2018-01-01')),
                ('create_time', models.DateTimeField(default='2018-01-01')),
                ('price', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PianoRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(default='', max_length=255, unique=True)),
                ('piano_type', models.TextField(default='')),
                ('brand', models.TextField(default='')),
                ('price_0', models.IntegerField(default=0)),
                ('price_1', models.IntegerField(default=0)),
                ('price_2', models.IntegerField(default=0)),
                ('art_ensemble', models.IntegerField(default=0)),
                ('usable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(default='', max_length=255, unique=True)),
                ('identity', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('permission', models.IntegerField(default=0)),
                ('session', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='piano_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.PianoRoom'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
        migrations.AddField(
            model_name='longtermorder',
            name='piano_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.PianoRoom'),
        ),
        migrations.AddField(
            model_name='longtermorder',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
    ]
