# Generated by Django 2.1.3 on 2018-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
