# Generated by Django 2.1.3 on 2018-11-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='feedback_content',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='feedback_title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='news_content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='news_title',
        ),
    ]
