# Generated by Django 2.1.3 on 2018-11-12 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
        migrations.AddField(
            model_name='longtermorder',
            name='piano_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.PianoRoom'),
        ),
        migrations.AddField(
            model_name='longtermorder',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='piano_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.PianoRoom'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_end.User'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 44, 14, 209101)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 44, 14, 208477)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 44, 14, 208466)),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 44, 14, 208853)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 44, 14, 208075)),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 44, 14, 208063)),
        ),
    ]
