# Generated by Django 2.1.3 on 2018-11-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
