# Generated by Django 2.1.3 on 2018-11-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0002_auto_20181114_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoroom',
            name='room_num',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='open_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
