# Generated by Django 2.1.3 on 2018-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0002_auto_20181124_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='order_permission',
            field=models.BooleanField(default=True),
        ),
    ]
