# Generated by Django 2.1.3 on 2018-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0002_auto_20181112_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='end_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='start_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='start_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(default=''),
        ),
    ]
