# Generated by Django 2.1.3 on 2018-11-12 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0003_auto_20181112_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 56, 56, 538727)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='end_date',
            field=models.DateField(default=datetime.date(2018, 11, 12)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 56, 56, 538106)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 11, 12)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 56, 56, 538095)),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 56, 56, 538481)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 12)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 56, 56, 537698)),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 56, 56, 537687)),
        ),
    ]
