# Generated by Django 2.1.3 on 2018-11-12 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0004_auto_20181112_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 57, 49, 928891)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 57, 49, 928242)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 57, 49, 928232)),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 57, 49, 928638)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 57, 49, 927827)),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 57, 49, 927816)),
        ),
    ]
