# Generated by Django 2.1.3 on 2018-11-12 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0005_auto_20181112_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 58, 52, 753135)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 58, 52, 752502)),
        ),
        migrations.AlterField(
            model_name='longtermorder',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 58, 52, 752492)),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 58, 52, 752887)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 58, 52, 752086)),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 19, 58, 52, 752075)),
        ),
    ]
